# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playgraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BggPlay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='playgraph.BggUser')),
            ],
        ),
    ]
