# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playgraph', '0002_bggplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='BggThing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
                ('year_published', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='bggplay',
            name='thing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playgraph.BggThing'),
        ),
    ]
